/home/csh/anaconda3/envs/tfgpu/bin/python run_classifier.py \
  --data_dir=data/ \
  --task_name=csv \
  --vocab_file=data/chinese_L-12_H-768_A-12/vocab.txt \
  --bert_config_file=data/chinese_L-12_H-768_A-12/bert_config.json \
  --output_dir=data/out2/ \
  --do_train=true \
  --do_eval=true \
  --init_checkpoint=data/chinese_L-12_H-768_A-12/bert_model.ckpt \
  --max_seq_length=300 \
  --train_batch_size=8 \
  --learning_rate=5e-5 \
  --num_train_epochs=3.0
